### ISSUE TITLE
[Action]: Get Terminating PODs

### ISSUE THREAD

**Issue by harshal-netserv** [unskript/Awesome-CloudOps-Automation#723]
### HealthCheck

- [X] Is this Action a Check Action?

### Action Name

Get Terminating PODs

### Action Inputs

namespace

### Action Outputs

list of dict with details of pods

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shloka-bhalgat-unskript** [comment]
I had a doubt regarding getting terminating pods from Kubernetes- So, as per my understanding a pod can have a Failed status when all containers in the Pod have terminated, and at least one container has terminated in failure. Whereas a container has a Terminated status. So for a lego where we want to get all terminated pods, what should be the selection criteria?
Reference- https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/
https://classic.shoreline.io/solutions/pods-stuck-in-terminating as for this reference, they are suggesting that the pods are stuck in terminating state  because the underlying node is likely broken :confused: . So what should the approach be here to find these terminating pods?

**Comment by shloka-bhalgat-unskript** [comment]
Actions exists [here](https://github.com/unskript/Awesome-CloudOps-Automation/tree/master/Kubernetes/legos/k8s_get_pods_in_terminating_state). Closing this issue
